# inspiration from gwfforg/gwf
name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: excitedleigh/setup-nox@0.1.0
      - name: Run tests
        run: nox
