# inspiration from gwforg/gwf
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: excitedleigh/setup-nox@1.0.0
      - name: Tests
        run: nox
